//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQDataaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQDatabase
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public int ThumbsUp { get; set; }
        public int ThumbsDown { get; set; }
    }
}
