//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQDataaccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NewQuestion
    {
        public int Id { get; set; }
        [RegularExpression(@"[A-Za-z]{2,50}",
        ErrorMessage = "Ugyldig Navn")]
        [Required(ErrorMessage = "Navn må oppgis")]
        [Display(Name = "Fornavn")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Epost må oppgis")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}",
        ErrorMessage = "Ugyldig epost adresse")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Feltet må fylles ut")]
        public string Question { get; set; }
    }
}
